Update apply_ruleset.yml to include API calls for rulesets

diff --git a/.github/workflows/apply_ruleset.yml b/.github/workflows/apply_ruleset.yml
--- a/.github/workflows/apply_ruleset.yml
+++ b/.github/workflows/apply_ruleset.yml
@@ -22,10 +22,16 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${{ github.repository }}/rulesets")
           echo "$EXIST"
-          #RESPONSE=$(curl -s -X POST \
-          #  -H "Accept: application/vnd.github.v3+json" \
-          #  -H "Authorization: Bearer $GITHUB_TOKEN" \
-          #  "https://api.github.com/repos/${{ github.repository }}/rulesets" \
-          #  -d @.github/rulesets/gitflow-ruleset.json)
-          #echo "$RESPONSE"
-          #echo "$RESPONSE" | grep "Invalid" && exit 1 || exit 0
+          RESPONSE=$(curl -s -X POST \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            "https://api.github.com/repos/${{ github.repository }}/rulesets" \
+            -d @.github/rulesets/gitflow-ruleset.json)
+          echo "$RESPONSE"
+          echo "$RESPONSE" | grep "Invalid" && exit 1 || exit 0
+          EXIST1=$(curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/${{ github.repository }}/rulesets")
+          echo "$EXIST1"
