Update apply_ruleset.yml to create or update GitFlow Enforcement ruleset

diff --git a/.github/workflows/apply_ruleset.yml b/.github/workflows/apply_ruleset.yml
--- a/.github/workflows/apply_ruleset.yml
+++ b/.github/workflows/apply_ruleset.yml
@@ -16,22 +16,26 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GIT_FLOW_PAT }}
         run: |
-          EXIST=$(curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer $GITHUB_TOKEN" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/${{ github.repository }}/rulesets")
-          echo "$EXIST"
-          RESPONSE=$(curl -s -X POST \
+          RULESET_NAME="GitFlow Enforcement"
+          RULESETS=$(curl -s -X GET \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
-            "https://api.github.com/repos/${{ github.repository }}/rulesets" \
-            -d @.github/rulesets/gitflow-ruleset.json)
-          echo "$RESPONSE"
-          echo "$RESPONSE" | grep "Invalid" && exit 1 || exit 0
-          EXIST1=$(curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer $GITHUB_TOKEN" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${{ github.repository }}/rulesets")
-          echo "$EXIST1"
+          RULESET_ID=$(echo "$RULESETS" | jq -r '.[] | select(.name=="'$RULESET_NAME'") | .id')
+          if [ -z "$RULESET_ID" ]; then
+            echo "Ruleset does not exist, creating..."
+            RESPONSE=$(curl -s -X POST \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: Bearer $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${{ github.repository }}/rulesets" \
+              -d @.github/rulesets/gitflow-ruleset.json)
+          else
+            echo "Ruleset exists, updating..."
+            RESPONSE=$(curl -s -X PATCH \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: Bearer $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${{ github.repository }}/rulesets/$RULESET_ID" \
+              -d @.github/rulesets/gitflow-ruleset.json)
+          fi
+          echo "$RESPONSE"
+          echo "$RESPONSE" | grep -q "Invalid" && exit 1 || exit 0
